<?php
/** op-unit-curl:/testcase/index.phtml
 *
 * @created   2020-03-01
 * @version   1.0
 * @package   op-unit-curl
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;

?>
<ul>
	<?php foreach(['api','get','post','cookie'] as $name): ?>
	<li><a href="<?= $name ?>"><?= $name ?></a></li>
	<?php endforeach; ?>
</ul>
